/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as campaignFactorySol from "./CampaignFactory.sol";
export type { campaignFactorySol };
export type { Campaign } from "./Campaign";
