/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as campaignFactorySol from "./CampaignFactory.sol";
export { Campaign__factory } from "./Campaign__factory";
